

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/latihandocker
    username: postgres
    password: rahasia

  # JPA
  jpa:
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      # Hibernate (create, create-drop, validate, update, none)
      ddl-auto: create-drop


server:
  error:
    include-message: always
  servlet:
    context-path: /api
  port: 8182
# error IllegalStateException


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE